export const STATUS_OPEN = 'STATUS_OPEN';
export const STATUS_ACTIVE = 'STATUS_ACTIVE';
export const STATUS_ONREVIEW = 'STATUS_ONREVIEW';
export const STATUS_BACKLOG = 'STATUS_BACKLOG';
export const STATUS_COMPLETED = 'STATUS_COMPLETED';